### ISSUE TITLE
if subsume process fails, terraform destroys your RDS database AND all backups

### ISSUE THREAD

**Issue by sbogar-shs** [pivotal-cf/docs-csb-aws#13]
Please create instructions for offloading your RDS backups and how to recover the instance in the legacy broker if the subsume process fails due to an intermittent or otherwise undected error. 

example doc could be something like:
WARNING:  the subsume process can potentially be a destructive one.  We recommend creating a manual backup of your RDS instance before attempting this procedure.  See the AWS doc [here](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_CommonTasks.BackupRestore.html)

In our case, we hit
Error creating DB Subnet Group: DBSubnetQuotaExceededFault: Your specified number of subnets is
greater than the limit of 20 DB subnets per group.

At this point the subsume process deleted the RDS instance and all of its backups making recovery impossible.

**Comment by snneji** [comment]
Hi @sbogar-shs, thanks for raising this issue. I'll pass this on to the engineering team and let you know about any update to the docs related to this issue.

**Comment by omerbensaadon** [comment]
this is fixed!

**Comment by omerbensaadon** [comment]
@sbogar-shs this was fixed as a part of https://github.com/cloudfoundry-incubator/cloud-service-broker/pull/150

Do you still feel this documentation is necessary? 

CC: @erniebilling

**Comment by snneji** [comment]
I added a warning note to the docs -- backing up the database is probably the safest thing to do. 

Closing the issue.
