### ISSUE TITLE
Index page does not mention requirement for external MySQL DB

### ISSUE THREAD

**Issue by coffee-squirrel** [pivotal-cf/docs-csb-aws#15]
As of 1.0.0, Tanzu Cloud Service Broker for AWS requires an externally-provided MySQL database for broker state.  This is mentioned on the [Installing and Configuring page](https://docs.pivotal.io/csb-aws/1-0/installing-with-aws.html#state-db), but not in the [Requirements section of the index page](https://docs.pivotal.io/csb-aws/1-0/index.html#reqs).

**Comment by jncd** [comment]
@omerbensaadon

**Comment by jncd** [comment]
Hello @coffee-squirrel 
We've added the database requirement to the index page now too.
Thanks for calling this out.
